const viewer=document.getElementById('desk'),button=document.getElementById('ar'),status=document.getElementById('status');
let selected='200';
function selectSize(value){if(!['180','200'].includes(String(value)))throw new Error('اختر 180 أو 200');selected=String(value);document.querySelectorAll('input[name=size]').forEach(e=>e.checked=e.value===selected);button.disabled=true;button.textContent='جاري تجهيز المقاس…';document.getElementById('loading').hidden=false;viewer.src=`./desk-${selected}.glb`;document.getElementById('dimensions').textContent=`${selected==='200'?'٢٠٠':'١٨٠'} عرض × ٨٠ عمق × ٧٥ ارتفاع — سم`;return {widthCm:Number(selected),depthCm:80,heightCm:75,topThicknessCm:2.5};}
document.querySelectorAll('input[name=size]').forEach(e=>e.addEventListener('change',()=>selectSize(e.value)));
viewer.addEventListener('load',()=>{document.getElementById('loading').hidden=true;button.disabled=false;button.textContent='شوفه في غرفتك';status.textContent=viewer.canActivateAR?'جاهز. افتح الكاميرا ووجّهها نحو الأرضية.':'المعاينة ثلاثية الأبعاد جاهزة. تجربة الكاميرا تحتاج جوالًا ومتصفحًا يدعمان الواقع المعزّز.';});
viewer.addEventListener('error',()=>{document.getElementById('loading').textContent='تعذّر تحميل المكتب. حدّث الصفحة للمحاولة مرة أخرى.';button.disabled=true;status.textContent='تأكد من اتصال الإنترنت ثم حدّث الصفحة.';});
button.addEventListener('click',async()=>{if(!viewer.canActivateAR){status.textContent='افتح نفس الرابط على جوالك: Safari لآيفون أو Chrome لأندرويد المدعوم.';return;}try{await viewer.activateAR();}catch(e){status.textContent='تعذّر بدء تجربة الكاميرا. جرّب فتح الرابط في متصفح الجوال مباشرة.';}});
viewer.addEventListener('ar-status',e=>{if(e.detail.status==='failed')status.textContent='لم تبدأ تجربة الواقع المعزّز على هذا الجهاز. يمكنك تدوير المكتب هنا أو التجربة على جوال آخر.';});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_desk_size',description:'Select the desk width and update the visible 3D preview.',inputSchema:{type:'object',properties:{widthCm:{type:'number',enum:[180,200]}},required:['widthCm'],additionalProperties:false},execute:async input=>{const result=selectSize(input.widthCm);await new Promise((resolve,reject)=>{viewer.addEventListener('load',resolve,{once:true});viewer.addEventListener('error',reject,{once:true});});return result;}})).catch(()=>{});}catch(e){}}
